export const Types = {
    LOGIN_USER: "LOGIN_USER",
    GET_USER: "GET_USER",
    SET_COMPANY: "SET_COMPANY",
    SET_USER_ERROR: "SET_USER_ERROR",
    LOG_OUT: "LOG_OUT",
    SET_COMPANY_USERS: "SET_COMPANY_USERS",

    LOADING_ON: "LOADING_ON",
    LOADING_OFF: "LOADING_OFF",
};
