export const TYPE = "TYPE";

export const Types = {
    TYPE: "TYPE",
    LOGIN_USER:'LOGIN_USER',
    GET_USER:'GET_USER',
    SET_USER_LOGGED_IN:'SET_USER_LOGGED_IN',
    SET_USER:'SET_USER',
    SET_USER_ERROR:'SET_USER_ERROR',
    LOG_OUT:'LOG_OUT',
    LOADING_ON:'LOADING_ON',
    LOADING_OFF:'LOADING_OFF',


};
